Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -78,7 +78,7 @@ jobs:
       - name: Test SQL Server Connection
         run: |
           echo "Testing SQL Server connection..."
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST,$DB_PORT -U $DB_USER -P $DB_PASS -d $DB_NAME -Q "SELECT 'Connection Successful' AS Status" || { echo 'SQL Connection Failed'; exit 1; }
+          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST,$DB_PORT -U $DB_USER -P $DB_PASS -d $DB_NAME -C -N -Q "SELECT 'Connection Successful' AS Status" || { echo 'SQL Connection Failed'; exit 1; }
 
       # Setup .NET SDKs (Install both .NET 9.0.x and .NET 8.0.x)
       - name: Setup .NET SDKs
